# action.yml
name: 'thiago-scherrer/climateclock-g-action'
description: 'Action to update markdown with climateclock.world'

inputs:
  branch:
    description: 'Branch to pull and push. Default main'
    required: false
    default: 'main'
  js_delay:
    description: 'Javascript delay in seconds. Default 3000'
    required: false
    default: '3000'

runs:
  using: "composite"
  steps:
    - run: git pull origin ${{ inputs.branch }}
      shell: bash

    - run: |
        docker run -v "$(pwd):/app" -e JS_DELAY=${{ inputs.js_delay }} \
        ghcr.io/thiago-scherrer/climateclock-gh-action:main 
      shell: bash

    - run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add clock.png
        git commit -m "chore: clock update"
        git push origin ${{ inputs.name }}
      shell: bash
