# action.yml
name: 'thiago-scherrer/climateclock-g-action'
description: 'Action to update markdown with climateclock.world'
runs:
  using: "composite"
  steps:
    - run: docker run \
      -v "$(pwd):/app" \
      -w /app \
      ghcr.io/thiago-scherrer/climateclock-gh-action:main \
      /bin/bash -c "wkhtmltoimage --transparent --javascript-delay 3000 --format png --quality 0 clock.html clock.png && \
      git config --global user.name 'GitHub Actions' && \
      git config --global user.email 'actions@github.com' && \
      git add clock.png && \
      git commit -m 'chore: clock update' && \
      git push origin main"

      shell: bash