# action.yml
name: 'thiago-scherrer/climateclock-g-action'
description: 'Action to update markdown with climateclock.world'
runs:
  using: "composite"
  steps:
    - run: docker run ghcr.io/thiago-scherrer/climateclock-gh-action:main ls
      shell: bash